Multi-instancing in SlackWare
git-svn-id: file:///home/asfernandes/fb/repository/sf/svn/firebird/trunk@30904 de594faa-8d1b-4a0c-9a6a-a7de5f8bf859

diff --git a/builds/install/arch-specific/linux/misc/firebird.init.d.slackware.in b/builds/install/arch-specific/linux/misc/firebird.init.d.slackware.in
--- a/builds/install/arch-specific/linux/misc/firebird.init.d.slackware.in
+++ b/builds/install/arch-specific/linux/misc/firebird.init.d.slackware.in
@@ -5,15 +5,33 @@
 # Start/stop/restart the firebird super server.
 #
 
-export FIREBIRD=@prefix@
+# To run more instances of firebird:
+#   Copy @prefix@ somewhere
+#   Copy this script under a new name
+#   Change INSTANCE and FIREBIRD below (all instance names should be unique)
+#   Edit the copied firebird.conf to change at least RemoteServicePort
+#   Optionally run rc-update to autostart the new service
+INSTANCE=default
+FIREBIRD=@prefix@
+
+# No changes needed below for multiple instances
 FBRunUser=firebird
-pidfile=/var/run/firebird/`basename $0`.pid
+pidfile=/var/run/firebird/$INSTANCE.pid
+FULLNAME="Firebird server [$INSTANCE]"
+LD_LIBRARY_PATH=$FIREBIRD/lib
+
+export FIREBIRD LD_LIBRARY_PATH
+
+MANAGER=$FIREBIRD/bin/fbmgr.bin
+
+# Check the file is there and is executable.
+[ -x $MANAGER ] || exit 0
 
 case "$1" in
-	'start')	echo -n "Starting Firebird server: "
-			echo $FIREBIRD/bin/fbmgr -pidfile $pidfile -start -forever | su $FBRunUser ;;
-	'stop')		echo -n "Stopping Firebird server: "
-			if [ -f $pidfile ]; then kill `cat $pidfile`; fi ;;
+	'start')	echo -n "Starting $FULLNAME: "
+			echo $MANAGER -pidfile $pidfile -start -forever | su $FBRunUser ;;
+	'stop')		echo -n "Stopping $FULLNAME: "
+			if [ -f $pidfile ]; then kill `cat $pidfile`; echo "done."; else echo "error: no PID file."; fi ;;
 	'restart')	$0 stop ; sleep 1; $0 start ;;
 	*)		echo "usage $0 start|stop|restart" ;;
 esac
