1. Deeper integration between super and classic setup. 2. Script to switch between classic and superclassic modes. 3. Changed lisences from LGPL to IDPL (with Mark's agreement)
git-svn-id: file:///home/asfernandes/fb/repository/sf/svn/firebird/trunk@35112 de594faa-8d1b-4a0c-9a6a-a7de5f8bf859

diff --git a/builds/install/arch-specific/linux/misc/linuxLibrary.sh.in b/builds/install/arch-specific/linux/misc/linuxLibrary.sh.in
--- a/builds/install/arch-specific/linux/misc/linuxLibrary.sh.in
+++ b/builds/install/arch-specific/linux/misc/linuxLibrary.sh.in
@@ -1,4 +1,26 @@
 #!/bin/sh
+#
+#  The contents of this file are subject to the Initial
+#  Developer's Public License Version 1.0 (the "License");
+#  you may not use this file except in compliance with the
+#  License. You may obtain a copy of the License at
+#  http://www.ibphoenix.com/main.nfs?a=ibphoenix&page=ibp_idpl.
+#
+#  Software distributed under the License is distributed AS IS,
+#  WITHOUT WARRANTY OF ANY KIND, either express or implied.
+#  See the License for the specific language governing rights
+#  and limitations under the License.
+#
+#  The Original Code was created by Mark O'Donohue
+#  for the Firebird Open Source RDBMS project.
+#
+#  Copyright (c) Mark O'Donohue <mark.odonohue@ludwig.edu.au>
+#  and all contributors signed below.
+#
+#  All Rights Reserved.
+#  Contributor(s): ______________________________________.
+#		Alex Peshkoff
+#
 
 RunUser=firebird
 export RunUser
@@ -119,7 +141,7 @@ getInitScriptLocation() {
 #  stop super server if it is running
 
 stopSuperServerIfRunning() {
-    checkString=`ps -efww| egrep "\b(fbserver|fbguard)\b" |grep -v grep`
+	checkString=`ps -eaf | egrep "\b(fbserver|fbguard|fb_smp_server)\b" |grep -v grep`
 
     if [ ! -z "$checkString" ]
     then
@@ -132,7 +154,7 @@ stopSuperServerIfRunning() {
 			do
        	    	$init_d stop
 				sleep 1
-				checkString=`ps -efww| egrep "\b(fbserver|fbguard)\b" |grep -v grep`
+				checkString=`ps -eaf | egrep "\b(fbserver|fbguard|fb_smp_server)\b" |grep -v grep`
 				if [ -z "$checkString" ]
 				then
 					return
@@ -175,3 +197,213 @@ generateNewDBAPassword() {
 
     writeNewPassword $NewPasswd
 }
+
+#------------------------------------------------------------------------
+#  change init.d RunUser
+
+changeInitRunUser() {
+    NewUser=$1
+
+    InitFile=`getInitScriptLocation`
+    if [ -f "$InitFile" ]
+    then
+        editFile "$InitFile" FBRunUser "FBRunUser=$NewUser"
+	    chmod u=rwx,g=rx,o= "$InitFile"
+    fi
+}
+
+
+#------------------------------------------------------------------------
+# installInitdScript
+# Everbody stores this one in a seperate location, so there is a bit of
+# running around to actually get it for each packager.
+# Update rcX.d with Firebird initd entries
+# initd script for SuSE >= 7.2 is a part of RPM package
+
+installInitdScript() {
+	Arch=$1
+	if [ "$Arch" != super ]; then
+		return 0
+	fi
+
+	srcScript=""
+	initScript=
+
+# This is for RH and MDK specific
+
+    if [ -e /etc/rc.d/init.d/functions ]
+    then
+        srcScript=firebird.init.d.mandrake
+        initScript=/etc/rc.d/init.d/firebird
+
+# SuSE specific
+
+    elif [ -r /etc/SuSE-release ]
+    then
+        srcScript=firebird.init.d.suse
+        initScript=/etc/init.d/firebird
+        rm -f /usr/sbin/rcfirebird
+        ln -s ../../etc/init.d/firebird /usr/sbin/rcfirebird
+
+# Debian specific
+
+    elif [ -r /etc/debian_version ]
+    then
+        srcScript=firebird.init.d.debian
+        initScript=/etc/init.d/firebird
+        rm -f /usr/sbin/rcfirebird
+        ln -s ../../etc/init.d/firebird /usr/sbin/rcfirebird
+
+# Slackware specific
+
+    elif [ -r /etc/slackware-version ]
+    then
+        srcScript=firebird.init.d.slackware
+        initScript=/etc/rc.d/rc.firebird
+		rclocal=/etc/rc.d/rc.local
+		if ! grep -q "$initScript" $rclocal
+		then
+			cat >>$rclocal <<EOF
+if [ -x $initScript ] ; then
+	$initScript start
+fi
+EOF
+		fi
+
+# Gentoo specific
+
+    elif [ -r /etc/gentoo-release ]
+    then
+        srcScript=firebird.init.d.gentoo
+        initScript=/etc/init.d/firebird
+
+# Generic...
+
+    elif [ -d /etc/rc.d/init.d ]
+    then
+        srcScript=firebird.init.d.generic
+        initScript=/etc/rc.d/init.d/firebird
+    fi
+
+	
+	if [ "$initScript" ]
+	then
+	    # Install the firebird init.d script
+    	cp $FBRootDir/misc/$srcScript $initScript
+	    chown root:root $initScript
+    	chmod ug=rx,o=r $initScript
+
+
+	    # RedHat and Mandrake specific 
+    	if [ -x /sbin/chkconfig ]
+	    then
+    	    /sbin/chkconfig --add firebird
+
+	    # Gentoo specific 
+    	elif [ -x /sbin/rc-update ]
+	    then
+			/sbin/rc-update add firebird default
+
+	    # Suse (& Debian ?) specific 
+    	elif [ -x /sbin/insserv ]
+	    then
+    	    /sbin/insserv /etc/init.d/firebird
+	
+		# One more way to register service - used in Knoppix (& Debian ?)
+    	elif [ -x /usr/sbin/update-rc.d ]
+	    then
+			/usr/sbin/update-rc.d firebird start 14 2 3 5 . stop 20 0 1 6 .
+	    fi
+	
+    	# More SuSE - rc.config fillup
+	    if [ -f /etc/rc.config ]
+    	then
+      		if [ -x /bin/fillup ]
+	        then
+    	      /bin/fillup -q -d = /etc/rc.config $FBRootDir/misc/rc.config.firebird
+        	fi
+	    elif [ -d /etc/sysconfig ]
+    	then
+        	cp $FBRootDir/misc/rc.config.firebird /etc/sysconfig/firebird
+	    fi
+	
+	else
+		echo "Couldn't autodetect linux type. You must select"
+		echo "the most appropriate startup script in $FBRootDir/misc/"
+		echo "and manually register it in your OS."
+	fi
+
+    # Create directory to store pidfile
+	if [ ! -d $PidDir ] 
+	then
+		[ -e $PidDir ] && rm -rf $PidDir
+		mkdir $PidDir
+	fi
+    chown $RunUser:$RunGroup $PidDir
+}
+
+
+#------------------------------------------------------------------------
+#  start init.d service
+
+startService() {
+	Arch=$1
+	if [ "$Arch" != super ]; then
+		return 0
+	fi
+
+    InitFile=`getInitScriptLocation`
+    if [ -f "$InitFile" ]
+    then
+		"$InitFile" start
+
+		checkString=`ps -eaf | egrep "\b(fbserver|fb_smp_server)\b" |grep -v grep`
+		if [ -z "$checkString" ]
+		then
+			# server didn't start - possible reason bad shell /bin/false for user "firebird"
+			echo
+			echo Fixing firebird\'s shell to /bin/sh
+			echo
+			usermod -s /bin/sh firebird
+			"$InitFile" start
+		fi
+	fi
+}
+
+#------------------------------------------------------------------------
+# If we have right systems remove the service autostart stuff.
+
+removeServiceAutostart() {
+	InitFile=`getInitScriptLocation`
+	if [ -f "$InitFile" ]; then
+
+		# Unregister using OS command
+		if [ -x /sbin/insserv ]; then
+			/sbin/insserv /etc/init.d/
+		fi
+     
+		if [ -x /sbin/chkconfig ]; then
+			/sbin/chkconfig --del firebird
+		fi
+
+		if [ -x /sbin/rc-update ]; then
+			/sbin/rc-update del firebird
+		fi
+
+		# Remove /usr/sbin/rcfirebird symlink
+		if [ -e /usr/sbin/rcfirebird ]
+		then
+			rm -f /usr/sbin/rcfirebird
+		fi
+        
+		# Remove initd script
+		if [ -e /etc/init.d/firebird ]; then
+			rm -f /etc/init.d/firebird
+		fi
+
+		if [ -e /etc/rc.d/init.d/firebird ]; then
+			rm -f /etc/rc.d/init.d/firebird
+		fi
+	fi
+}
+
