Frontported CORE-3467: provide a silent install switch
git-svn-id: https://firebird.svn.sourceforge.net/svnroot/firebird/firebird/trunk@53041 de594faa-8d1b-4a0c-9a6a-a7de5f8bf859

diff --git a/builds/install/misc/posixLibrary.sh.in b/builds/install/misc/posixLibrary.sh.in
--- a/builds/install/misc/posixLibrary.sh.in
+++ b/builds/install/misc/posixLibrary.sh.in
@@ -830,3 +830,32 @@ updateInetdServiceEntry() {
 		fi
     fi
 }
+
+
+#------------------------------------------------------------------------
+#  parseArgs
+#  Parse passed arguments.
+#  Set appropriate global flags.
+
+parseArgs() {
+	flSilent=0
+
+	while [ -n "$1" ]; do
+		case $1 in
+			-silent)
+				flSilent=1
+				;;
+			*)
+				echo "Invalid option: $1. Known option is '-silent'."
+				exit 1
+				;;
+		esac
+		shift
+	done
+
+	if [ $flSilent -eq 0 ]; then
+		InteractiveInstall=1
+		export InteractiveInstall
+	fi
+}
+
